//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudjettI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menot
    {
        public int MenotID { get; set; }
        public int AsiakasID { get; set; }
        public int MenolajitID { get; set; }
        public Nullable<System.DateTime> PVM { get; set; }
        public string Maara { get; set; }
    
        public virtual Asiakas Asiakas { get; set; }
        public virtual Menolajit Menolajit { get; set; }
    }
}
