//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudjettI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BudjektiBDEntities : DbContext
    {
        public BudjektiBDEntities()
            : base("name=BudjektiBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asiakas> Asiakas { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Menolajit> Menolajit { get; set; }
        public virtual DbSet<Menot> Menot { get; set; }
        public virtual DbSet<Tulolajit> Tulolajit { get; set; }
        public virtual DbSet<Tulot> Tulot { get; set; }
    }
}
